### ISSUE TITLE
根目录书签显示缺失

### ISSUE THREAD

**Issue by antnesswcm** [X-X-X-X-X-X-X-X-X-X-X-X-X/Bookmark#3]
![image](https://github.com/user-attachments/assets/8bffe870-84a2-4091-b344-fdd3965d04e1)

![image](https://github.com/user-attachments/assets/bc57e45b-b0d8-4ed9-8c51-94e0b6893fa6)

> 1.5.1到1.5.2新版本 bookmark的根目录的显示书签少一个错误，旧版本bookmark根目录的会显示三个书签。

**Comment by X-X-X-X-X-X-X-X-X-X-X-X-X** [comment]
好的，将在下个版本修复

**Comment by X-X-X-X-X-X-X-X-X-X-X-X-X** [comment]
已提交审核，将在1.5.2.1版本恢复
