### ISSUE TITLE
提个建议，固定横向布局大小，来减少视觉重新定位

### ISSUE THREAD

**Issue by alem0n** [X-X-X-X-X-X-X-X-X-X-X-X-X/Bookmark#4]
建议：横向布局的大小固定为最大。
原因：当前逻辑是当文件夹内书签很少时会缩小，这样前一个文件夹内容很多界面为最大，然后切换目录后界面变小，这样视觉上来回移动长久用会造成疲劳。

**Comment by X-X-X-X-X-X-X-X-X-X-X-X-X** [comment]
好的，下个版本出个固定宽度的设置选项（虽然我觉得怪怪的🤣）

**Comment by X-X-X-X-X-X-X-X-X-X-X-X-X** [comment]
[dist.zip](https://github.com/user-attachments/files/16457431/dist.zip)

这个文件默认为最大宽度，你可以在 edge://extensions 该页面打开开发人员模式，然后点击加载解压缩的扩展进行使用，我认为效果不太理想。

**Comment by X-X-X-X-X-X-X-X-X-X-X-X-X** [comment]
已发布
