### ISSUE TITLE
Purify Bookmark View 优化书签显示

### ISSUE THREAD

**Issue by ilovecxty** [X-X-X-X-X-X-X-X-X-X-X-X-X/Bookmark#5]
The maximum number of rows displayed by bookmarks seems to be fixed at the moment, and it can be changed to user-configurable

目前书签显示的最大行数似乎是固定的，能否改成用户可配置的？

**Comment by X-X-X-X-X-X-X-X-X-X-X-X-X** [comment]
齿轮图标设置中可以调节书签列宽与间隙大小，调整后会发生改变
